  1. 看缺失值：df.isnull().sum()
  2. 填補數值缺失值：SimpleImputer(strategy='mean')
  3. 填補類別缺失值：SimpleImputer(strategy='most_frequent')
  4. 類別編碼：.map({'男':0, '女':1})
  5. 標準化：StandardScaler()

  numpy → 數學運算，處理純數字矩陣  
pandas → 處理有欄位名稱的表格資料  
         類似 Excel，但用程式操作  

競賽流程：  
  原始資料（CSV）  
    → 用 pandas 讀入、清理、前處理  
    → 轉成 numpy array  
    → 丟進 sklearn 模型訓練  

1. 建立資料表  
pythondf = pd.DataFrame(data)  
 把字典變成表格  
 有欄位名稱、有索引、好看好操作  
2. 檢查缺失值  
pythondf.isnull().sum()  
 numpy array 做不到這個  
 pandas 才有這個功能  
3. 選欄位操作  
pythondf[['年齡', '收入']]      # 選特定欄位  
df['性別'].map({...})     # 對某欄位做轉換  

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

data = {
    '年齡': [25, np.nan, 32, 28, 35, np.nan, 29],
    '收入': [50000, 80000, np.nan, 60000, np.nan, 70000, 55000],
    '性別': ['男', '女', '男', np.nan, '女', '男', '女'],
    '是否購買': ['是', '否', '是', '否', '是', '否', '是']
}

df = pd.DataFrame(data)
print(df)
print(f"\n缺失值數量:\n{df.isnull().sum()}")

     年齡       收入   性別 是否購買
0  25.0  50000.0    男    是
1   NaN  80000.0    女    否
2  32.0      NaN    男    是
3  28.0  60000.0  NaN    否
4  35.0      NaN    女    是
5   NaN  70000.0    男    否
6  29.0  55000.0    女    是

缺失值數量:
年齡      2
收入      2
性別      1
是否購買    0
dtype: int64


In [6]:
# 數值欄位用平均值填補
imputer = SimpleImputer(strategy='mean')
df[['年齡', '收入']] = imputer.fit_transform(df[['年齡', '收入']])

# 類別欄位用最常出現的值填補
imputer_cat = SimpleImputer(strategy='most_frequent')
df[['性別']] = imputer_cat.fit_transform(df[['性別']])

print(df)
print(f"\n缺失值數量:\n{df.isnull().sum()}")

     年齡       收入 性別 是否購買
0  25.0  50000.0  男    是
1  29.8  80000.0  女    否
2  32.0  63000.0  男    是
3  28.0  60000.0  女    否
4  35.0  63000.0  女    是
5  29.8  70000.0  男    否
6  29.0  55000.0  女    是

缺失值數量:
年齡      0
收入      0
性別      0
是否購買    0
dtype: int64


In [7]:
# 性別：男=0, 女=1
df['性別'] = df['性別'].map({'男': 0, '女': 1})

# 是否購買：否=0, 是=1
df['是否購買'] = df['是否購買'].map({'否': 0, '是': 1})

print(df)

     年齡       收入  性別  是否購買
0  25.0  50000.0   0     1
1  29.8  80000.0   1     0
2  32.0  63000.0   0     1
3  28.0  60000.0   1     0
4  35.0  63000.0   1     1
5  29.8  70000.0   0     0
6  29.0  55000.0   1     1


In [ ]:
X = df[['年齡', '收入', '性別']].values
y = df['是否購買'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("標準化前:")
print(X[:3])
print("\n標準化後:")
print(X_scaled[:3].round(2))

標準化前:
[[2.50e+01 5.00e+04 0.00e+00]
 [2.98e+01 8.00e+04 1.00e+00]
 [3.20e+01 6.30e+04 0.00e+00]]

標準化後:
[[-1.66 -1.43 -1.15]
 [-0.    1.87  0.87]
 [ 0.76  0.   -1.15]]


: 